name: Docker Build for PRs

on:
  push:
    branches:
    - '!main'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: docker build & push, kubectl apply
        run: |
          docker build -t levelupdevops-pr:${{ github.sha }} .
